# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: joda70/ngx-voms-build:latest

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - env
    - sh ${HOME}/build-install-ngx-voms.sh
    - mv ${HOME}/local local
  artifacts:
    paths:
      - local

test:
  stage: test
  dependencies:
    - build
  script:
    - rm -rf ${HOME}/local/
    - mv local ${HOME}
    - sh test-ngx-voms.sh

coverage:
  stage: test
  script:
    - env
    - sh ${HOME}/build-install-ngx-voms.sh -d -c
    - sh test-ngx-voms.sh
    - sh cov-ngx-voms.sh
    - mv cov coverage
  artifacts:
    paths:
      - coverage

pages:
  stage: deploy
  dependencies:
    - coverage
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
