# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: storm2/ngx-voms-build:latest

stages:
  - build
  - test

#before_script:
#  - source ${HOME}/openresty-env
  
build:
  stage: build
  script:
    - env | sort
    - id
    # ngx_http_voms_module build
    - sh ${HOME}/build-install-ngx-voms.sh
    - cp -r ${HOME}/local local
  artifacts:
    paths:
      - local

test:
  stage: test
  dependencies:
    - build
  script:
    - id
    - source ${HOME}/openresty-env
    - env | sort
    - ls -al . 
    - ls -al local
    - cp -r local ${HOME}/local
    # ngx_http_voms_module test
    #- sh ${HOME}/build-install-ngx-voms.sh
    - cp -r t /tmp
    - cd /tmp
    - prove -v
