# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: storm2/ngx-voms-build:latest

stages:
  - build
  - test

build:
  stage: build
  script:
    - env
    - sh ${HOME}/build-install-ngx-voms.sh
    - mv ${HOME}/local local
  artifacts:
    paths:
      - local

test:
  stage: test
  dependencies:
    - build
  script:
    - mv -f local/* ${HOME}/local/
    - sh test-ngx-voms.sh
