
stages:
  - build-ngx
  - build-voms
  - docker-build

build-ngx-httpg-rpm:
  stage: build-ngx
  image: centos:7
  script: 
    - env | sort
    - sh docker/library-scripts/provide-deps.sh
    - pwd && echo ${CI_PROJECT_DIR}
    - sh rpm/build-httpg-nginx-rpm.sh
    - mkdir ngx-artifacts
    - cp rpmbuild/SRPMS/* ngx-artifacts/
    - cp rpmbuild/RPMS/x86_64/* ngx-artifacts/
  artifacts:
    paths:
      - ngx-artifacts/

build-voms-rpm:
  stage: build-voms
  image: centos:7
  script:
    - env | sort
    - sh docker/library-scripts/provide-deps.sh
    - sh rpm/build-voms-rpm.sh
    - mkdir voms-artifacts
    - cp rpmbuild/SRPMS/* voms-artifacts/
    - cp rpmbuild/RPMS/x86_64/* voms-artifacts/
  artifacts:
    paths:
      - voms-artifacts/

build-container:
  stage: docker-build
  image: docker:latest
  services:
    - name: docker:dind
      command: ["--tls=false"]
  dependencies:
    - build-ngx-httpg-rpm
    - build-voms-rpm
  script:
    - apk add git bash
    - git clone https://baltig.infn.it/mw-devel/helper-scripts.git helper-scripts
    - cp helper-scripts/scripts/* /usr/local/bin
    - cp ngx-artifacts/* ${CI_PROJECT_DIR}/docker/
    - cp voms-artifacts/* ${CI_PROJECT_DIR}/docker/
