# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: storm2/ngx-voms-build:latest

stages:
  - build
  - test

build:
  stage: build
  script:
    - sh ${HOME}/build-install-ngx-voms.sh
    - cp -r ${HOME}/local localtemp
  artifacts:
    paths:
      - localtemp

test:
  stage: test
  dependencies:
    - build
  script:
    - cp -r localtemp ${HOME}/local
    - chmod +x ${HOME}/local/openresty/bin/openresty
    - chmod +x ${HOME}/local/openresty/nginx/sbin/nginx
    - source ${HOME}/openresty-env
    - which openresty
    - env | sort
    #- sh ${HOME}/build-install-ngx-voms.sh
    - cp -r t /tmp
    - cd /tmp
    - prove -v
